---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-memory
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:beta-*
spec:
  releaseName: ngsa-memory
  chart:
    git: git@github.com:retaildevcrews/ngsa-cd
    path: charts/ngsa
    ref: main
  values:
    app:
      args: []
      secretName: ngsa-secrets
      repository: retaildevcrew/ngsa-app
      tag: beta-0.0.8-0111-1435-141
    ds:
      args: [ "--in-memory" ]
      secretName: ngsa-secrets
      repository: retaildevcrew/ngsa-dataservice
      tag: beta-0.0.8-0111-0907-139
    cert:
      issuer: letsencrypt-prod
      name: ngsa-mem-cert
    ingress:
      hosts:
      - ngsa-mem-dev.cse.ms
      paths:
      - /
      tls:
        httpsRedirect: true
