---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-cosmos
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
    #fluxcd.io/tag.chart-image: glob:beta-*
spec:
  releaseName: ngsa-cosmos
  chart:
    git: git@github.com:retaildevcrews/ngsa-cd
    path: charts/ngsa
    ref: main
  values:
    app:
      args: []
      secretName: ngsa-secrets
    cert:
      issuer: letsencrypt-prod
      name: ngsa-cos-cert
    image:
      name: ngsa
      repository: retaildevcrew
      tag: beta-0.0.8-1214-1721-90
    ingress:
      hosts:
      - ngsa-cos-dev.cse.ms
      paths:
      - /
      tls:
        httpsRedirect: true
