---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-cosmos
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:beta-*
spec:
  releaseName: ngsa-cosmos
  chart:
    git: git@github.com:retaildevcrews/ngsa-cd
    path: charts/ngsa
    ref: main
  values:
    app:
      args: []
      region: Central
      secretName: ngsa-secrets
      zone: Az-CentralUS
    cert:
      issuer: letsencrypt-prod
      name: ngsa-cos-cert
    image:
      repository: retaildevcrew/ngsa
      tag: beta-0.0.8-1215-1726-106
    ingress:
      hosts:
      - ngsa-cos-pre-central.cse.ms
      paths:
      - /
      tls:
        httpsRedirect: true
