---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-memory
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:beta-*
spec:
  releaseName: ngsa-memory
  chart:
    git: git@github.com:retaildevcrews/ngsa-cd
    path: charts/ngsa
    ref: main
  values:
    app:
      args: ["--in-memory"]
      region: East
      secretName: ngsa-secrets
      zone: Az-EastUS2
    cert:
      issuer: letsencrypt-prod
      name: ngsa-mem-cert
    image:
      repository: retaildevcrew/ngsa
      tag: beta-0.0.8-1215-1940-114
    ingress:
      hosts:
      - ngsa-mem-pre-east.cse.ms
      paths:
      - /
      tls:
        httpsRedirect: true
